### PR TITLE
Adds pagination

### PR DESCRIPTION
**Pull request by OwenRay**

### CODE REVIEW

**Comment by dennybiasiolli** [comment]
Hi @OwenRay, is this PR related to this issue? https://github.com/Bardavon-Health/actions-aws-ssm-params-to-env/issues/56

If so, I'd like to merge it to a fork of this repo I made, to increase the speed of updates.
I decided to fork (again) the repo and release an updated version of the GitHub action here: [Fingerprint-Compliance/actions-aws-ssm-params-to-env@v1.5.1](https://github.com/Fingerprint-Compliance/actions-aws-ssm-params-to-env/releases/tag/v1.5.1)

I'd like to merge your changes as well in the next release, what do you think?

Meanwhile I'm trying to contact one of the maintainers (@chough-bardavon) to ask him if it's possible for me to maintain this repo, so we can use the official one and not a fork.

**Comment by OwenRay** [comment]
Hi @dennybiasiolli 
it's related to that indeed.
Feel free to merge it to your branche.
would be nice to have an up-to-date official version indeed, hopefully @chough-bardavon  will respond on that.

**Comment by dennybiasiolli** [comment]
Hi @OwenRay, they included me as a collaborator in this repository, so I can help them check pull requests and merge things 😉 
Can you please rebase your pull request here on top of the last commit on branch master?
After that I will be happy to merge this pull request and release an updated version 🎉

**Comment by FedericoSinisi** [comment]
@OwenRay :pray:

**Comment by OwenRay** [comment]
Sorry, somehow missed this; but I see you got it sorted, great to have it merged upstream.

**Pull request closed without merging**
