### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by dennybiasiolli**
This will close the following pull requests opened by @dependabot

- [Bump actions/checkout from v3.1.0 to v3](https://github.com/Bardavon-Health/actions-aws-ssm-params-to-env/pull/17/commits/b1b23d13acb4e82b2d6e3f4c4dc90efa8b29f5c9) (Close #13)
- [Bump aws-actions/configure-aws-credentials from 1 to 2](https://github.com/Bardavon-Health/actions-aws-ssm-params-to-env/pull/17/commits/976f976a3d83cc82a494466a4f678d713e45bdf9) (Close #15)
- [Bump aws-sdk from 2.1229.0 to 2.1414.0](https://github.com/Bardavon-Health/actions-aws-ssm-params-to-env/pull/17/commits/be304b60f539b1b53425a3be3a1618bcb693b900) (Close #16)
- [removing aws-sdk dependency](https://github.com/Bardavon-Health/actions-aws-ssm-params-to-env/pull/17/commits/36936362c5888ab721606605025d194474b1e489) 
    AWS is formalizing their plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023
    
    Ref. https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html
- [upgrading code to use @aws-sdk/client-ssm](https://github.com/Bardavon-Health/actions-aws-ssm-params-to-env/pull/17/commits/3a12677a39b01183e04cbf232f101db2a8d3868e)

### CODE REVIEW

**Comment by dennybiasiolli** [comment]
@chough-bardavon not sure why tests are not working here, but I tried these changes in a github actions using our fork and everything is working fine, with a lot less node_modules files! 💪

**Comment by dennybiasiolli** [comment]
@chough-bardavon I don't have the action in the repository, I used the new version in another repo pointing to `IP-Sentinel/actions-aws-ssm-params-to-env@v1.5.0` and it works without errors, getting parameters in the correct way

**Comment by dennybiasiolli** [comment]
Maybe the `secrets.AWS_DEFAULT_REGION` is null, check your repository settings

**Comment by chough-bardavon** [comment]
> Maybe the `secrets.AWS_DEFAULT_REGION` is null, check your repository settings

Yeah that was my first thought. I updated the value to `us-east-1` and got the same error. Re-created the secret and it's value as well to no avail.

**Review by chough-bardavon — APPROVED** [review]

**Pull request merged**
