### PR TITLE
Uplift repository (node, libs, build and release)

### PR DESCRIPTION
**Pull request by sammcj**
I have uplifted this repo with a number of updates and minor improvements.

Note that there are no changes to the javascript code itself.

- Update Action to a supported node version (16)
- Update libraries to their current, stable versions
- Remove the need for committing node_modules to the git repo by using ncc at build time
	- Removed the node_modules directory (hence Github thinking there are 1682 files changed).
- Add .nvmrc with supported node version
- Add .gitignore to ignore build artifacts
- Update the main build/deploy workflow
	- Use setup-node for the build
	- Run on master and main branches as well as develop
	- On master/main only:
		- Automatically tag the action
		- Automatically release the action
- Fix markdown formatting (markdown lint)

---

If @Bardavon-Health is no longer using this Action, I would be happy to take over ownership and maintain it.

### CODE REVIEW

**Comment by sammcj** [comment]
cc/ @rhenry-bardavon & @nathanshire as I can't request you as reviewers 😄

**Comment by sammcj** [comment]
And just after submitting this I noticed your fork @dennybiasiolli 🥲

**Comment by dennybiasiolli** [comment]
@sammcj they merged my fork in the main branch and released a `v1.3` 🥳 

You can switch back to this official version with

```yml
- uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.3
```

**Comment by chough-bardavon** [comment]
Closing this PR since it's been a while and there are now a bunch of merge conflicts and certain things are no longer applicable. Feel free to re-submit a new PR if desired.

**Pull request closed without merging**
